### ISSUE TITLE
Malformed links in RSS feed

### ISSUE THREAD

**Issue by ssimono** [dragan-stepanovic/dragan-stepanovic.github.io#1]
Hi Dragan,

I wanted to add the [RSS feed](https://dragan-stepanovic.github.io/feed.xml) of your blog to my RSS reader (because your blog is great) and I noticed that the links it contains are malformed: They contain the website url followed by the full url of each item, which themselves contain the website url.

![screenshot](https://user-images.githubusercontent.com/2179169/83514346-c34ed680-a4d3-11ea-949e-d29a2e5bda8b.png)

It might be due to [prepending the url and the baseurl](https://github.com/dragan-stepanovic/dragan-stepanovic.github.io/blob/master/feed.xml#L20) to links.

Have a nice day

**Comment by dragan-stepanovic** [comment]
Thanks Simon! Just fixed it, hope it's fine now.
And thanks for subscribing :)

**Comment by ssimono** [comment]
It is fine indeed, thanks
