### ISSUE TITLE
Broken "About" and "Subscribe" links

### ISSUE THREAD

**Issue by Minoru** [dragan-stepanovic/dragan-stepanovic.github.io#2]
"About" and "Subscribe" links point to www.draganstepanovic.com which responds with 404 Not Found. Perhaps `baseurl` should point to GitHub Pages?

https://github.com/dragan-stepanovic/dragan-stepanovic.github.io/blob/98ba727938a99d194461607ce56477294902e972/_config.yml#L9

I enjoy your blog. Didn't know it's legal to write such short posts :D

**Comment by dragan-stepanovic** [comment]
Fixed as part of the other issue.
Thanks for carving out the time to read my blog. I try to make them short in order not to procrastinate with longer ones, and I guess a bonus side-effect is that readers don't have to allocate a lot of time to read them. Small batches :)
