### ISSUE TITLE
Broken URLs in RSS items

### ISSUE THREAD

**Issue by Minoru** [dragan-stepanovic/dragan-stepanovic.github.io#3]
The two posts published today are linked to:

- http://www.draganstepanovic.com/2021/11/15/you-might-think-small-prs-are-good.html
- http://www.draganstepanovic.com/2021/11/15/assume-you-are-wrong

However, these URLs respond with code 404.

There is a redirect from www.draganstepanovic.com to dragan-stepanovic.github.io, but it somehow doesn't cover anything but the main page.

(The fix is probably the same as #2.)

**Comment by dragan-stepanovic** [comment]
Thanks, @Minoru for reporting this. The baseurl in the config file for Jekyll was making a problem. Should be fixed now.
